import {
  ProgramNode,
  ASTNode,
  StructNode,
  FuncNode,
  VarDeclNode,
  TypeAliasNode,
  InterfaceNode
} from "../ast";

export class JSGenerator {
  public generate(ast: ProgramNode): string {
    const lines: string[] = [];

    lines.push("// Generated by Hatchet 1.2 JS target");
    lines.push("'use strict';\n");

    for (const node of ast.body) {
      lines.push(this.visit(node));
    }

    return lines.join("\n\n");
  }

  private visit(node: ASTNode): string {
    switch (node.type) {
      case "TypeAlias":
      case "Interface":
        return "";

      case "Struct":
        return this.genStruct(node as StructNode);

      case "Func":
        return this.genFunc(node as FuncNode);

      case "VarDecl":
        return this.genVarDecl(node as VarDeclNode);

      case "Literal":
        return typeof node.value === "string" ? `"${node.value}"` : node.value;

      case "Identifier":
        return node.name;

      default:
        return "";
    }
  }

  private genStruct(node: StructNode): string {
    const lines: string[] = [];
    const isValStruct = node.isValStruct;

    lines.push(`class ${node.name} {`);
    lines.push(`  constructor(init = {}) {`);

    const propNames: string[] = [];
    for (const member of node.members) {
      if (member.type === "VarDecl") {
        const v = member as VarDeclNode;
        propNames.push(v.name);
        const initVal = v.value ? this.visit(v.value) : "null";
        lines.push(`    this.${v.name} = init.${v.name} !== undefined ? init.${v.name} : ${initVal};`);
      }
    }

    lines.push(`  }`);

    if (isValStruct) {
      lines.push(``);
      lines.push(`  clone() {`);
      lines.push(`    return new ${node.name}({`);
      for (const prop of propNames) {
        lines.push(`      ${prop}: this.${prop},`);
      }
      lines.push(`    });`);
      lines.push(`  }`);
    }

    for (const member of node.members) {
      if (member.type === "Func") {
        const f = member as FuncNode;
        lines.push(this.genMethod(f));
      }
    }

    lines.push(`}`);
    return lines.join("\n");
  }

  private genMethod(node: FuncNode): string {
    if (node.isHeaderSignature || !node.body) return "";

    const asyncPrefix = node.isAsync ? "async " : "";
    const staticPrefix = node.isStatic ? "static " : "";
    const paramsStr = node.params.map((p) => p.name).join(", ");

    const lines: string[] = [];
    lines.push(`\n  ${staticPrefix}${asyncPrefix}${node.name}(${paramsStr}) {`);
    for (const stmt of node.body) {
      lines.push(`    ${this.visit(stmt)}`);
    }
    lines.push(`  }`);

    return lines.join("\n");
  }

  private genFunc(node: FuncNode): string {
    if (node.isHeaderSignature || !node.body) return "";

    const asyncPrefix = node.isAsync ? "async " : "";
    const paramsStr = node.params.map((p) => p.name).join(", ");
    const lines: string[] = [];

    lines.push(`${asyncPrefix}function ${node.name}(${paramsStr}) {`);
    for (const stmt of node.body) {
      lines.push(`  ${this.visit(stmt)}`);
    }
    lines.push(`}`);

    return lines.join("\n");
  }

  private genVarDecl(node: VarDeclNode): string {
    const valStr = node.value ? this.visit(node.value) : "undefined";
    return `let ${node.name} = ${valStr};`;
  }
}